apiVersion: v1
kind: ConfigMap
metadata:
  namespace: juno-app
  name: juno-config
data:
  port: "8000"
  session-expires-in: "1d"
  google-callback-url: "https://juno-hieu261204.xyz/api/auth/google/callback"
  frontend-origin: "https://juno-hieu261204.xyz"
  frontend-google_callback_url: "https://juno-hieu261204.xyz/google/callback"
